[package]
name = "example-websocket-chat"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
poem = { workspace = true, features = ["websocket"]}
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
futures-util.workspace = true
tracing-subscriber.workspace = true
