[package]
name = "example-websocket-chat"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
poem = { path = "../../../poem", features = ["websocket"]}
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
futures-util.workspace = true
tracing-subscriber.workspace = true
