[package]
name = "example-openapi-custom-payload"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bcs = "0.1.3"
mime.workspace = true
poem = { path = "../../../poem" }
poem-openapi = { path = "../../../poem-openapi" }
serde.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync"] }

