[package]
name = "examples-worker-hello-world"
version = "0.1.0"
edition = "2024"
rust-version = "1.94"
publish = false

[workspace]
resolver = "2"

[package.metadata.release]
release = false

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = { version = "0.8.7" }
poem = { path = "../../../poem", default-features = false }
poem-worker = { path = "../../../poem-worker" }
