[package]
name = "example-openapi-content-type-accept"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
bcs = "0.1.3"
mime.workspace = true
poem.workspace = true
poem-openapi.workspace = true
serde.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync"] }
