[package]
name = "counter"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
poem-mcpserver.workspace = true
serde.workspace = true
schemars.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync"] }
