[workspace]
resolver = "2"
members = ["poem/*", "openapi/*", "grpc/*", "mcpserver/*"]
exclude = ["poem/worker-hello-world"]

[workspace.package]
version = "0.1.0"
edition = "2021"
publish = false

[workspace.dependencies]
poem = { path = "../poem" }
poem-grpc = { path = "../poem-grpc" }
poem-openapi = { path = "../poem-openapi", features = ["swagger-ui"] }
poem-lambda = { path = "../poem-lambda" }
poem-grpc-build = { path = "../poem-grpc-build" }
poem-mcpserver = { path = "../poem-mcpserver" }
poem-worker = { path = "../poem-worker" }

tokio = "1.53.1"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
serde_json = "1.0.151"
serde = { version = "1.0.229", features = ["derive"] }
mime = "0.3.17"
open = "5.4.4"
futures-util = "0.3.34"
tokio-stream = "0.1.19"
prost = "0.14.4"
