[package]
name = "example-openapi-auth-multiple"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
jwt = "0.15.0"
poem = { path = "../../../poem" }
poem-openapi = { path = "../../../poem-openapi", features = ["swagger-ui"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing-subscriber.workspace = true
hmac = "0.11"
sha2 = "0.9"
serde.workspace = true
