[package]
name = "poem-todos"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
poem = { path = "../../../poem" }
poem-openapi = { path = "../../../poem-openapi" }
sqlx = { version = "0.6.0", features = ["runtime-tokio-rustls", "sqlite"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tokio-stream.workspace = true
