[package]
name = "example-middleware-fn"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
poem = { path = "../../../poem" }
tokio = { version = "1.17.0", features = ["rt-multi-thread", "macros"] }
tracing-subscriber = { version ="0.3.9", features = ["env-filter"] }
