[package]
name = "poem-grpc"
version = "0.6.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "GRPC support for Poem."
keywords = ["http", "async", "grpc"]
categories = ["network-programming", "asynchronous"]

[features]
default = []
json-codec = ["serde", "serde_json"]
gzip = ["async-compression/gzip"]
deflate = ["async-compression/deflate"]
brotli = ["async-compression/brotli"]
zstd = ["async-compression/zstd"]
example_generated = []

[dependencies]
poem = { workspace = true, default-features = true }

futures-util.workspace = true
async-stream = "0.3.6"
tokio = { workspace = true, features = ["io-util", "rt", "sync", "net"] }
itoa = "1.0.18"
percent-encoding = "2.3.2"
bytes.workspace = true
prost = "0.14.4"
base64.workspace = true
prost-types = "0.14.4"
tokio-stream = { workspace = true, features = ["sync"] }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
rustls = { workspace = true }
thiserror.workspace = true
fastrand = "2.5.0"
http.workspace = true
hyper = { version = "1.11.1", features = ["http1", "http2"] }
hyper-util = { version = "0.1.21", features = ["client-legacy", "tokio"] }
http-body-util = "0.1.5"
tokio-rustls.workspace = true
tower-service = "0.3.3"
webpki-roots = "1.0.9"
async-compression = { version = "0.4.50", optional = true, features = ["tokio"] }
sync_wrapper = { version = "1.0.2", features = ["futures"] }

[build-dependencies]
poem-grpc-build.workspace = true

[package.metadata.workspaces]
independent = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
