[package]
name = "example-tera-templating"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
poem = { workspace = true, features = ["rustls"]}
tokio = { workspace = true, features = ["full"] }
tera = "1.17.1"
lazy_static = "1.4.0"
