[package]
name = "example-tera-templating"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
poem = { path = "../../../poem" }
tokio = { workspace = true, features = ["full"] }
tera = "1.17.1"
once_cell = "1.17.0"
