[package]
name = "example-tera-templating"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
poem.workspace = true
tokio = { workspace = true, features = ["full"] }
tera = "1.17.1"
once_cell = "1.17.0"
