[package]
name = "example-tera-templating"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
poem = { path = "../../../poem", features = ["rustls"]}
tokio = { version = "1.21.2", features = ["full"] }
tera = "1.17.1"
lazy_static = "1.4.0"
